server:
  port: 8081
spring:
  application:
    name: yh-movie-service
  jackson:
    date-format: yyyy-MM-hh HH:mm:ss
    time-zone: Asia/Shanghai
  profiles:
    active: dev
  #  配置Mysql数据库的连接信息
  datasource:
    url: jdbc:mysql://${yhmovie.db.host}:${yhmovie.db.port}/${yhmovie.db.name}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${yhmovie.db.username}
    password: ${yhmovie.db.password}
  # Redis配置
  data:
    redis:
      host: localhost           # Redis 服务器地址
      port: 6378              # Redis 服务器连接端口
      password: 123456               # Redis 服务器连接密码（默认为空）
      database: 2              # Redis 数据库索引（选择数据库 1）
      connect-timeout: 10000   # 连接超时时间（毫秒）
      client-type: lettuce     # 使用 lettuce 客户端
      lettuce:
        pool:
          enabled: true        # 启用连接池
          max-active: 8        # 连接池最大连接数
          max-wait: -1ms       # 连接池最大阻塞等待时间（负值表示没有限制）
          max-idle: 8          # 连接池中的最大空闲连接
          min-idle: 0          # 连接池中的最小空闲连接

# MyBatis-Plus的配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yhmovie.service.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
